export const testData = [
    {
        id: 1,
        system_name: '정보계_IQ',
        enroll: 1,
        dbms_dbname: 'POSTIQ',
        server_name: 'iq110_01',
        tbl_owner: 'Post',
        tbl_name: 'ACCOUNT',
        tbl_desc: '계정',
        trrule_yn: 'YES',
        tx_yn: 'YES',
        ledger: '내역',
        status: '신규',
        truncate_yn: 'YES',
        extract_sql: '"select * from \\"ACCOUNT\\" where col_1 > 10"',
        users: '5',
        real_size: '8',
        dev_size: '7',
        users_query: [
            {
                uid: 'manager',
                extract_sql: 'select * from "ACCOUNT" where acnt_cnt > 10',
            },
            {
                uid: 'officer',
                extract_sql: 'select * from "ACCOUNT" where account_name like "%ACNT_%"',
            },
            {
                uid: 'postuser',
                extract_sql: 'select * from "ACCOUNT" where acnt_type = "user"',
            },
            {
                uid: 'workman',
                extract_sql: 'select * from "ACCOUNT" where acnt_cnt > 999',
            },
            {
                uid: 'user',
                extract_sql: 'select * from "ACCOUNT" where acnt_no in (20,21,22)"',
            },
        ],
    },
    {
        id: 2,
        system_name: '정보계_IQ',
        enroll: 0,
        dbms_dbname: 'POSTIQ',
        server_name: 'iq110_01',
        tbl_owner: 'Post',
        tbl_name: 'EMP',
        tbl_desc: '사원 테이블',
        trrule_yn: 'YES',
        tx_yn: 'YES',
        ledger: '내역',
        status: '신규',
        truncate_yn: 'YES',
        extract_sql: '"select * from \\"EMP\\" where col_1 > 10"',
        users: '1',
        real_size: '36',
        dev_size: '34',
        users_query: [
            {
                userid: 'postUser',
                user_extract_sql: '"select * from \'EMP\' where count > 10"',
            },
        ],
    },
    {
        id: 3,
        system_name: '정보계_IQ',
        enroll: 0,
        dbms_dbname: 'POSTIQ',
        server_name: 'iq110_01',
        tbl_owner: 'Post',
        tbl_name: 'CUST_BASE',
        tbl_desc: '기본 고객 테이블',
        trrule_yn: 'YES',
        tx_yn: 'YES',
        ledger: '',
        status: '변경',
        truncate_yn: 'YES',
        extract_sql: '"select * from \\"CUST_BASE\\" where col_1 > 10"',
        users: '3',
        real_size: '14',
        dev_size: '13',
        users_query: [
            {
                userid: 'postUser',
                user_extract_sql: '"select * from \'CUST_BASE\' where count > 10"',
            },
            {
                userid: 'postUser',
                user_extract_sql: '"select * from \'EMP_CORP\' where count > 10"',
            },
            {
                userid: 'postUser',
                user_extract_sql: '"select * from \'EMP_CORP\' where count > 10"',
            },
        ],
    },
    {
        id: 4,
        system_name: '정보계_IQ',
        enroll: 0,
        dbms_dbname: 'POSTIQ',
        server_name: 'iq110_01',
        tbl_owner: 'Post',
        tbl_name: 'CUST_CORP',
        tbl_desc: '고객 기업 테이블',
        trrule_yn: 'YES',
        tx_yn: 'YES',
        ledger: '내역',
        truncate_yn: 'YES',
        extract_sql: '"select * from \\"CUST_CORP\\" where col_1 > 10"',
        users: '2',
        real_size: '9',
        dev_size: '7',
        users_query: [
            {
                userid: 'postUser',
                user_extract_sql: '"select * from \'CUST_CORP\' where count > 10"',
            },
            {
                userid: 'postUser',
                user_extract_sql: '"select * from \'EMP_CORP\' where count > 10"',
            },
        ],
    },
    {
        id: 5,
        system_name: '정보계_IQ',
        enroll: 1,
        dbms_dbname: 'POSTIQ',
        server_name: 'iq110_01',
        tbl_owner: 'Post',
        tbl_name: 'CUST_ACT',
        tbl_desc: '고객 행동 테이블',
        trrule_yn: 'YES',
        tx_yn: 'YES',
        ledger: '',
        truncate_yn: 'YES',
        extract_sql: '"select * from \\"CUST_BASE\\" where col_1 > 10"',
        users: '2',
        real_size: '24',
        dev_size: '26',
        users_query: [
            {
                userid: 'postUser',
                user_extract_sql: '"select * from \'CUST_BASE\' where count > 10"',
            },
            {
                userid: 'postUser',
                user_extract_sql: '"select * from \'EMP_CORP\' where count > 10"',
            },
        ],
    },
    {
        id: 6,
        system_name: '정보계_IQ',
        enroll: 1,
        dbms_dbname: 'POSTIQ',
        server_name: 'iq110_01',
        tbl_owner: 'Post',
        tbl_name: 'CUST_SWAP',
        tbl_desc: '고객 변경 테이블',
        trrule_yn: 'YES',
        tx_yn: 'YES',
        ledger: '',
        truncate_yn: 'YES',
        extract_sql: '"select * from \\"CUST_SWAP\\" where col_1 > 10"',
        users: '1',
        real_size: '29',
        dev_size: '26',
        users_query: [
            {
                userid: 'postUser',
                user_extract_sql: '"select * from \'CUST_SWAP\' where count > 10"',
            },
        ],
    },
    {
        id: 7,
        system_name: '정보계_IQ',
        enroll: 1,
        dbms_dbname: 'POSTIQ',
        server_name: 'iq110_01',
        tbl_owner: 'Post',
        tbl_name: 'CUST_TRD',
        tbl_desc: '고객 트레이딩 테이블',
        trrule_yn: 'YES',
        tx_yn: 'YES',
        ledger: '',
        status: '신규',
        truncate_yn: 'YES',
        extract_sql: '"select * from \\"CUST_TRD\\" where col_1 > 10"',
        users: '1',
        real_size: '31',
        dev_size: '28',
        users_query: [
            {
                userid: 'postUser',
                user_extract_sql: '"select * from \'CUST_TRD\' where count > 10"',
            },
        ],
    },

    {
        id: 8,
        system_name: '정보계_IQ',
        enroll: 0,
        dbms_dbname: 'POSTIQ',
        server_name: 'iq110_01',
        tbl_owner: 'Post',
        tbl_name: 'EMP_BASE',
        tbl_desc: '기본 사원 테이블',
        trrule_yn: 'YES',
        tx_yn: 'YES',
        ledger: '내역',
        truncate_yn: 'YES',
        extract_sql: '"select * from \\"EMP_BASE\\" where col_1 > 10"',
        users: '6',
        real_size: '7',
        dev_size: '4',
        users_query: [
            {
                uid: 'postUser',
                extract_sql: '"select * from \'EMP_BASE\' where count > 10"',
            },
            {
                userid: 'postUser',
                user_extract_sql: '"select * from \'EMP_CORP\' where count > 10"',
            },
        ],
    },
    {
        id: 9,
        system_name: '정보계_IQ',
        enroll: 0,
        dbms_dbname: 'POSTIQ',
        server_name: 'iq110_01',
        tbl_owner: 'Post',
        tbl_name: 'EMP_CORP',
        tbl_desc: '사원 기업 테이블',
        trrule_yn: 'YES',
        tx_yn: 'YES',
        ledger: '내역',
        truncate_yn: 'YES',
        extract_sql: '"select * from \\"EMP_CORP\\" where col_1 > 10"',
        users: '3',
        real_size: '19',
        dev_size: '21',
        users_query: [
            {
                userid: 'postUser',
                user_extract_sql: '"select * from \'EMP_CORP\' where count > 10"',
            },
            {
                userid: 'postUser',
                user_extract_sql: '"select * from \'EMP_CORP\' where count > 10"',
            },
        ],
    },
    {
        id: 10,
        system_name: '정보계_IQ',
        enroll: 1,
        dbms_dbname: 'POSTIQ',
        server_name: 'iq110_01',
        tbl_owner: 'Post',
        tbl_name: 'EMP_ACT',
        tbl_desc: '사원 행동 테이블',
        trrule_yn: 'YES',
        tx_yn: 'YES',
        ledger: '',
        status: '변경',
        truncate_yn: 'YES',
        extract_sql: '"select * from \\"EMP_ACT\\" where col_1 > 10"',
        users: '4',
        real_size: '41',
        dev_size: '39',
        users_query: [
            {
                userid: 'postUser',
                user_extract_sql: '"select * from \'EMP_ACT\' where count > 10"',
            },
            {
                userid: 'postUser',
                user_extract_sql: '"select * from \'EMP_CORP\' where count > 10"',
            },
        ],
    },
    {
        id: 11,
        system_name: '정보계_IQ',
        enroll: 1,
        dbms_dbname: 'POSTIQ',
        server_name: 'iq110_01',
        tbl_owner: 'Post',
        tbl_name: 'EMP_SWAP',
        tbl_desc: '사원 변경 테이블',
        trrule_yn: 'YES',
        tx_yn: 'YES',
        ledger: '',
        truncate_yn: 'YES',
        extract_sql: '"select * from \\"EMP_SWAP\\" where col_1 > 10"',
        users: '2',
        real_size: '17',
        dev_size: '14',
        users_query: [
            {
                userid: 'postUser',
                user_extract_sql: '"select * from \'EMP_SWAP\' where count > 10"',
            },
            {
                userid: 'postUser',
                user_extract_sql: '"select * from \'EMP_CORP\' where count > 10"',
            },
        ],
    },
    {
        id: 12,
        system_name: '정보계_IQ',
        enroll: 1,
        dbms_dbname: 'POSTIQ',
        server_name: 'iq110_01',
        tbl_owner: 'Post',
        tbl_name: 'EMP_TRD',
        tbl_desc: '사원 트레이딩 테이블',
        trrule_yn: 'YES',
        tx_yn: 'YES',
        ledger: '',
        truncate_yn: 'YES',
        extract_sql: '"select * from \\"EMP_TRD\\" where col_1 > 10"',
        users: '1',
        real_size: '22',
        dev_size: '22',
        users_query: [
            {
                userid: 'postUser',
                user_extract_sql: '"select * from \'CUST_TRD\' where count > 10"',
            },
        ],
    },
    {
        id: 13,
        system_name: '정보계_IQ',
        enroll: 0,
        dbms_dbname: 'POSTIQ',
        server_name: 'iq110_01',
        tbl_owner: 'Post',
        tbl_name: 'TOTAL_TABLE',
        tbl_desc: '전체 테이블',
        trrule_yn: 'YES',
        tx_yn: 'YES',
        ledger: '',
        truncate_yn: 'YES',
        extract_sql: '"select * from \\"EMP_TRD\\" where col_1 > 10"',
        users: '1',
        real_size: '22',
        dev_size: '22',
        users_query: [
            {
                userid: 'postUser',
                user_extract_sql: '"select * from \'CUST_TRD\' where count > 10"',
            },
        ],
    },
];

export const testSystem = [
    {
        system_name: '정보계_IQ',
        serverid_src: 'INFOIQ',
        serverid_dst: 'INFOIQ',
        owner_list: 'iq110, iq110_1, iq110_2',
    },
    {
        system_name: '계정계_IQ',
        serverid_src: 'ACNTIQ',
        serverid_dst: 'ACNTIQ',
        owner_list: 'acnt_origin, acnt_src, acnt_dst',
    },
    {
        system_name: 'CRM_IQ',
        serverid_src: 'CRM_IQ',
        serverid_dst: 'CRM_IQ',
        owner_list: 'fncrmdb, fncrmdb_acnt, fncrmdb_origin',
    },
    {
        system_name: '정보계_ORA',
        serverid_src: 'INFOORA',
        serverid_dst: 'INFOORA',
        owner_list: 'ora_110, ora_111, ora_112',
    },
    {
        system_name: '계정계_ORA',
        serverid_src: 'ACNTORA',
        serverid_dst: 'ACNTORA',
        owner_list: 'acnt_origin, acnt_src, acnt_dst',
    },
    {
        system_name: 'CRM_ORA',
        serverid_src: 'CRM_ORA',
        serverid_dst: 'CRM_ORA',
        owner_list: 'fncrmdb, fncrmdb_acnt, fncrmdb_origin',
    },
    {
        system_name: '정보계_TIBERO',
        serverid_src: 'INFOTIBERO',
        serverid_dst: 'INFOTIBERO',
        owner_list: 't_110, t_111, t_112',
    },
    {
        system_name: '계정계_TIBERO',
        serverid_src: 'ACNTTIBERO',
        serverid_dst: 'ACNTTIBERO',
        owner_list: 'acnt_origin, acnt_src, acnt_dst',
    },
    {
        system_name: 'CRM_TIBERO',
        serverid_src: 'CRM_TIBERO',
        serverid_dst: 'CRM_TIBERO',
        owner_list: 't_crmdb, t_crmdb_acnt, t_crmdb_origin',
    },
];

export const testSync = [
    {
        wname: '계정계 일배치',
        wdesc: '계정계 매일',
        pattern: '2',
        start_d: '2022-03-10',
        ehour: '13',
        emin: '00',
        end_d: '9999-12-13',
        status: '진행중',
        success_yn: '',
        next_run_dt: '2022-03-11',
        last_exe_dt: '2022-03-09',
    },
    {
        wname: '정보계 일배치',
        wdesc: '정보계 매일',
        pattern: '2',
        start_d: '2022-03-06',
        ehour: '11',
        emin: '00',
        end_d: '2023-03-06',
        status: '',
        success_yn: '성공',
        next_run_dt: '2022-03-11',
        last_exe_dt: '2022-03-09',
    },
    {
        wname: 'CRM 일배치',
        wdesc: 'CRM 매일',
        pattern: '2',
        start_d: '2022-01-01',
        ehour: '09',
        emin: '10',
        end_d: '2030-01-01',
        status: '',
        success_yn: '성공',
        next_run_dt: '2022-03-11',
        last_exe_dt: '2022-03-09',
    },
    {
        wname: '계정계 분기 스케줄',
        wdesc: '2022-03-18 Updated ',
        pattern: 5,
        start_d: '2022-03-03',
        ehour: '09',
        emin: '00',
        end_d: '2030-03-03',
        status: '',
        success_yn: '성공',
        next_run_dt: '2022-06-03',
        last_exe_dt: '2022-03-03',
    },
    {
        wname: '계정계 추가 스케줄',
        wdesc: 'UserInstance 추가',
        pattern: '1',
        start_d: '2022-03-10',
        ehour: '18',
        emin: '30',
        end_d: '2022-03-10',
        status: '만료',
        success_yn: '성공',
        next_run_dt: '',
        last_exe_dt: '2022-03-10',
    },
    {
        wname: 'CRM 자율 스케줄',
        wdesc: '2주 수금',
        pattern: '1',
        start_d: '2022-03-10',
        ehour: '08',
        emin: '30',
        end_d: '2032-03-10',
        status: '',
        success_yn: '성공',
        next_run_dt: '2022-03-11',
        last_exe_dt: '',
    },
];

export const testSyncDetail = [
    {
        system_name: '계정계_IQ',
        tbl_owner: 'Post',
        tbl_name: 'ACCOUNT',
        status: '성공',
        real_size: '21',
        dev_size: '19',
    },
    {
        system_name: '계정계_ORACLE',
        tbl_owner: 'Post',
        tbl_name: 'EMP',
        status: '진행중',
        real_size: '',
        dev_size: '',
    },
];

export const testMsg = [
    {
        type: 2,
        writer: 'admin',
        date: '2022-03-12 13:00',
        contents: '[마감 공지] 2022-02-12~2022-03-12 (기준일 : 2022-02-01) 마감되었습니다.',
        receiver: 'ehdtnn',
        read: 0,
    },
    {
        type: 1,
        writer: 'admin',
        date: '2022-03-05 10:22',
        contents: '작업 매니징 재요청 - 계정계 수정 요망',
        receiver: 'ehdtnn',
        read: 0,
    },
    {
        type: 1,
        writer: 'manager',
        date: '2022-03-04 11:40',
        contents: 'Post 작업 매니징 완료로 마감하시면 되겠습니다.',
        receiver: 'ehdtnn',
        read: 0,
    },
    {
        type: 1,
        writer: 'postuser',
        date: '2022-03-02 10:11',
        contents: '정보계ORA 작업 완료했습니다.',
        receiver: 'ehdtnn',
        read: 1,
    },
    {
        type: 1,
        writer: 'officer',
        date: '2022-03-02 08:30',
        contents: 'CRM 쿼리 수정에 따른 업무 개시 요청입니다.',
        receiver: 'ehdtnn',
        read: 1,
    },
    {
        type: 1,
        writer: 'officer',
        date: '2022-03-01 09:34',
        contents: 'CRM 작업 완료했습니다.',
        receiver: 'ehdtnn',
        read: 1,
    },
    {
        type: 2,
        writer: 'admin',
        date: '2022-03-01 11:25',
        contents: 'CRM 작업 재차 확인 부탁',
        receiver: 'ehdtnn',
        read: 0,
    },
    {
        type: 1,
        writer: 'postuser',
        date: '2022-02-28 16:20',
        contents: 'INFOORA 업무 및 스케줄 확인 부탁드립니다.',
        receiver: 'ehdtnn',
        read: 0,
    },
    {
        type: 2,
        writer: 'manager',
        date: '2022-02-28 12:31',
        contents: 'Trans POST 개시 및 마감, 업무 공지',
        receiver: 'ehdtnn',
        read: 1,
    },
    {
        type: 1,
        writer: 'manager',
        date: '2022-02-28 11:14',
        contents: 'Trans POST 개시에 대한 메세지',
        receiver: 'ehdtnn',
        read: 1,
    },
    {
        type: 2,
        writer: 'admin',
        date: '2022-02-26 13:25',
        contents: '[개시 공지] 2022-02-26~2022-03-12 (기준일 : 2022-01-01) 개시되었습니다.',
        receiver: 'ehdtnn',
        read: 1,
    },
    {
        type: 2,
        writer: 'admin',
        date: '2022-02-26 13:19',
        contents: '[마감 공지] 2022-02-12~2022-02-26 (기준일 : 2022-01-01) 마감되었습니다.',
        receiver: 'ehdtnn',
        read: 0,
    },
    {
        type: 1,
        writer: 'postuser',
        date: '2022-02-24 15:19',
        contents: 'ORACLE 컨설팅 서비스 사고 방식 채택',
        receiver: 'ehdtnn',
        read: 0,
    },
    {
        type: 1,
        writer: 'postuser',
        date: '2022-02-22 09:57',
        contents: 'CRM 테스트 보완 패치',
        receiver: 'ehdtnn',
        read: 1,
    },
    {
        type: 1,
        writer: 'manager',
        date: '2022-02-20 14:32',
        contents: '계정계 사용자 스케줄 주 2회 목금 확인 부탁드립니다.',
        receiver: 'ehdtnn',
        read: 0,
    },
    {
        type: 1,
        writer: 'manager',
        date: '2022-02-20 14:32',
        contents: '계정계 일배치 스케줄 확인 부탁드립니다.',
        receiver: 'ehdtnn',
        read: 1,
    },
    {
        type: 2,
        writer: 'admin',
        date: '2022-02-12 12:55',
        contents: '[개시 공지] 2022-02-12~2022-03-12 (기준일 : 2022-02-01) 개시되었습니다.',
        receiver: 'ehdtnn',
        read: 1,
    },
];
